name: Deploy to Cloudflare Workers

on: workflow_dispatch

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: graphql-ws.enisdenjo.workers.dev
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install
        run: yarn install --immutable
      - name: Deploy
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
        env:
          CF_ACCOUNT_ID: ${{secrets.CF_ACCOUNT_ID}}
